package bi.baiqiu.pojo.jd;

import java.util.Date;

public class JdToken {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.server_url
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private String serverUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.platform
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Byte platform;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.enabled
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Byte enabled;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.shop_id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Integer shopId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.repertory_name
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private String repertoryName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.appkey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private String appkey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.secretKey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private String secretkey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.accessToken
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private String accesstoken;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.modify_time
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bi_jd_token.modify
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	private Date modify;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.id
	 *
	 * @return the value of bi_jd_token.id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.id
	 *
	 * @param id
	 *            the value for bi_jd_token.id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.server_url
	 *
	 * @return the value of bi_jd_token.server_url
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public String getServerUrl() {
		return serverUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.server_url
	 *
	 * @param serverUrl
	 *            the value for bi_jd_token.server_url
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setServerUrl(String serverUrl) {
		this.serverUrl = serverUrl == null ? null : serverUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.platform
	 *
	 * @return the value of bi_jd_token.platform
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Byte getPlatform() {
		return platform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.platform
	 *
	 * @param platform
	 *            the value for bi_jd_token.platform
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setPlatform(Byte platform) {
		this.platform = platform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.enabled
	 *
	 * @return the value of bi_jd_token.enabled
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Byte getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.enabled
	 *
	 * @param enabled
	 *            the value for bi_jd_token.enabled
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.shop_id
	 *
	 * @return the value of bi_jd_token.shop_id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.shop_id
	 *
	 * @param shopId
	 *            the value for bi_jd_token.shop_id
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.repertory_name
	 *
	 * @return the value of bi_jd_token.repertory_name
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public String getRepertoryName() {
		return repertoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.repertory_name
	 *
	 * @param repertoryName
	 *            the value for bi_jd_token.repertory_name
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setRepertoryName(String repertoryName) {
		this.repertoryName = repertoryName == null ? null : repertoryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.appkey
	 *
	 * @return the value of bi_jd_token.appkey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public String getAppkey() {
		return appkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.appkey
	 *
	 * @param appkey
	 *            the value for bi_jd_token.appkey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setAppkey(String appkey) {
		this.appkey = appkey == null ? null : appkey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.secretKey
	 *
	 * @return the value of bi_jd_token.secretKey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public String getSecretkey() {
		return secretkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.secretKey
	 *
	 * @param secretkey
	 *            the value for bi_jd_token.secretKey
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setSecretkey(String secretkey) {
		this.secretkey = secretkey == null ? null : secretkey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.accessToken
	 *
	 * @return the value of bi_jd_token.accessToken
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public String getAccesstoken() {
		return accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.accessToken
	 *
	 * @param accesstoken
	 *            the value for bi_jd_token.accessToken
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken == null ? null : accesstoken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.modify_time
	 *
	 * @return the value of bi_jd_token.modify_time
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.modify_time
	 *
	 * @param modifyTime
	 *            the value for bi_jd_token.modify_time
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bi_jd_token.modify
	 *
	 * @return the value of bi_jd_token.modify
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public Date getModify() {
		return modify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bi_jd_token.modify
	 *
	 * @param modify
	 *            the value for bi_jd_token.modify
	 *
	 * @mbggenerated Fri Oct 20 16:05:21 CST 2017
	 */
	public void setModify(Date modify) {
		this.modify = modify;
	}

	public JdToken(String serverUrl, String accesstoken, String appkey, String secretkey) {
		this.serverUrl = serverUrl;
		this.appkey = appkey;
		this.secretkey = secretkey;
		this.accesstoken = accesstoken;
	}

}