package bi.baiqiu.pojo;

public class AddressVerification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_address_verification.id
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_address_verification.state
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_address_verification.mac_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    private String macAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_address_verification.ip_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    private String ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_address_verification.id
     *
     * @return the value of bi_address_verification.id
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_address_verification.id
     *
     * @param id the value for bi_address_verification.id
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_address_verification.state
     *
     * @return the value of bi_address_verification.state
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_address_verification.state
     *
     * @param state the value for bi_address_verification.state
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_address_verification.mac_address
     *
     * @return the value of bi_address_verification.mac_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_address_verification.mac_address
     *
     * @param macAddress the value for bi_address_verification.mac_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress == null ? null : macAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_address_verification.ip_address
     *
     * @return the value of bi_address_verification.ip_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_address_verification.ip_address
     *
     * @param ipAddress the value for bi_address_verification.ip_address
     *
     * @mbggenerated Fri Oct 27 17:37:03 CST 2017
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }
}