package bi.baiqiu.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JdOrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public JdOrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(Integer value) {
            addCriterion("pay_type =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(Integer value) {
            addCriterion("pay_type <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(Integer value) {
            addCriterion("pay_type >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_type >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(Integer value) {
            addCriterion("pay_type <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_type <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<Integer> values) {
            addCriterion("pay_type in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<Integer> values) {
            addCriterion("pay_type not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_type between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_type not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNull() {
            addCriterion("order_total_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNotNull() {
            addCriterion("order_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceEqualTo(BigDecimal value) {
            addCriterion("order_total_price =", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("order_total_price <>", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("order_total_price >", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_total_price >=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThan(BigDecimal value) {
            addCriterion("order_total_price <", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_total_price <=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIn(List<BigDecimal> values) {
            addCriterion("order_total_price in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("order_total_price not in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_total_price between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_total_price not between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIsNull() {
            addCriterion("order_payment is null");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIsNotNull() {
            addCriterion("order_payment is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentEqualTo(BigDecimal value) {
            addCriterion("order_payment =", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotEqualTo(BigDecimal value) {
            addCriterion("order_payment <>", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentGreaterThan(BigDecimal value) {
            addCriterion("order_payment >", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_payment >=", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLessThan(BigDecimal value) {
            addCriterion("order_payment <", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_payment <=", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIn(List<BigDecimal> values) {
            addCriterion("order_payment in", values, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotIn(List<BigDecimal> values) {
            addCriterion("order_payment not in", values, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_payment between", value1, value2, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_payment not between", value1, value2, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andFreightPriceIsNull() {
            addCriterion("freight_price is null");
            return (Criteria) this;
        }

        public Criteria andFreightPriceIsNotNull() {
            addCriterion("freight_price is not null");
            return (Criteria) this;
        }

        public Criteria andFreightPriceEqualTo(BigDecimal value) {
            addCriterion("freight_price =", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceNotEqualTo(BigDecimal value) {
            addCriterion("freight_price <>", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceGreaterThan(BigDecimal value) {
            addCriterion("freight_price >", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("freight_price >=", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceLessThan(BigDecimal value) {
            addCriterion("freight_price <", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("freight_price <=", value, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceIn(List<BigDecimal> values) {
            addCriterion("freight_price in", values, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceNotIn(List<BigDecimal> values) {
            addCriterion("freight_price not in", values, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("freight_price between", value1, value2, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andFreightPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("freight_price not between", value1, value2, "freightPrice");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIsNull() {
            addCriterion("seller_discount is null");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIsNotNull() {
            addCriterion("seller_discount is not null");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountEqualTo(BigDecimal value) {
            addCriterion("seller_discount =", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotEqualTo(BigDecimal value) {
            addCriterion("seller_discount <>", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountGreaterThan(BigDecimal value) {
            addCriterion("seller_discount >", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("seller_discount >=", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLessThan(BigDecimal value) {
            addCriterion("seller_discount <", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("seller_discount <=", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIn(List<BigDecimal> values) {
            addCriterion("seller_discount in", values, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotIn(List<BigDecimal> values) {
            addCriterion("seller_discount not in", values, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seller_discount between", value1, value2, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seller_discount not between", value1, value2, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("order_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("order_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("order_state =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("order_state <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("order_state >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("order_state >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("order_state <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("order_state <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("order_state like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("order_state not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("order_state in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("order_state not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("order_state between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("order_state not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNull() {
            addCriterion("order_remark is null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNotNull() {
            addCriterion("order_remark is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkEqualTo(String value) {
            addCriterion("order_remark =", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotEqualTo(String value) {
            addCriterion("order_remark <>", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThan(String value) {
            addCriterion("order_remark >", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("order_remark >=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThan(String value) {
            addCriterion("order_remark <", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThanOrEqualTo(String value) {
            addCriterion("order_remark <=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLike(String value) {
            addCriterion("order_remark like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotLike(String value) {
            addCriterion("order_remark not like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIn(List<String> values) {
            addCriterion("order_remark in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotIn(List<String> values) {
            addCriterion("order_remark not in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkBetween(String value1, String value2) {
            addCriterion("order_remark between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotBetween(String value1, String value2) {
            addCriterion("order_remark not between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIsNull() {
            addCriterion("order_start_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIsNotNull() {
            addCriterion("order_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeEqualTo(Date value) {
            addCriterion("order_start_time =", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotEqualTo(Date value) {
            addCriterion("order_start_time <>", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeGreaterThan(Date value) {
            addCriterion("order_start_time >", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_start_time >=", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLessThan(Date value) {
            addCriterion("order_start_time <", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_start_time <=", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIn(List<Date> values) {
            addCriterion("order_start_time in", values, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotIn(List<Date> values) {
            addCriterion("order_start_time not in", values, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeBetween(Date value1, Date value2) {
            addCriterion("order_start_time between", value1, value2, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_start_time not between", value1, value2, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIsNull() {
            addCriterion("order_end_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIsNotNull() {
            addCriterion("order_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeEqualTo(Date value) {
            addCriterion("order_end_time =", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotEqualTo(Date value) {
            addCriterion("order_end_time <>", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeGreaterThan(Date value) {
            addCriterion("order_end_time >", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_end_time >=", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLessThan(Date value) {
            addCriterion("order_end_time <", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_end_time <=", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIn(List<Date> values) {
            addCriterion("order_end_time in", values, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotIn(List<Date> values) {
            addCriterion("order_end_time not in", values, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeBetween(Date value1, Date value2) {
            addCriterion("order_end_time between", value1, value2, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_end_time not between", value1, value2, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoIsNull() {
            addCriterion("consignee_info is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoIsNotNull() {
            addCriterion("consignee_info is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoEqualTo(String value) {
            addCriterion("consignee_info =", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoNotEqualTo(String value) {
            addCriterion("consignee_info <>", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoGreaterThan(String value) {
            addCriterion("consignee_info >", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoGreaterThanOrEqualTo(String value) {
            addCriterion("consignee_info >=", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoLessThan(String value) {
            addCriterion("consignee_info <", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoLessThanOrEqualTo(String value) {
            addCriterion("consignee_info <=", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoLike(String value) {
            addCriterion("consignee_info like", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoNotLike(String value) {
            addCriterion("consignee_info not like", value, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoIn(List<String> values) {
            addCriterion("consignee_info in", values, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoNotIn(List<String> values) {
            addCriterion("consignee_info not in", values, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoBetween(String value1, String value2) {
            addCriterion("consignee_info between", value1, value2, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andConsigneeInfoNotBetween(String value1, String value2) {
            addCriterion("consignee_info not between", value1, value2, "consigneeInfo");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIsNull() {
            addCriterion("item_info_list is null");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIsNotNull() {
            addCriterion("item_info_list is not null");
            return (Criteria) this;
        }

        public Criteria andItemInfoListEqualTo(String value) {
            addCriterion("item_info_list =", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotEqualTo(String value) {
            addCriterion("item_info_list <>", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListGreaterThan(String value) {
            addCriterion("item_info_list >", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListGreaterThanOrEqualTo(String value) {
            addCriterion("item_info_list >=", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLessThan(String value) {
            addCriterion("item_info_list <", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLessThanOrEqualTo(String value) {
            addCriterion("item_info_list <=", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLike(String value) {
            addCriterion("item_info_list like", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotLike(String value) {
            addCriterion("item_info_list not like", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIn(List<String> values) {
            addCriterion("item_info_list in", values, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotIn(List<String> values) {
            addCriterion("item_info_list not in", values, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListBetween(String value1, String value2) {
            addCriterion("item_info_list between", value1, value2, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotBetween(String value1, String value2) {
            addCriterion("item_info_list not between", value1, value2, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIsNull() {
            addCriterion("vender_remark is null");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIsNotNull() {
            addCriterion("vender_remark is not null");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkEqualTo(String value) {
            addCriterion("vender_remark =", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotEqualTo(String value) {
            addCriterion("vender_remark <>", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkGreaterThan(String value) {
            addCriterion("vender_remark >", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("vender_remark >=", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLessThan(String value) {
            addCriterion("vender_remark <", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLessThanOrEqualTo(String value) {
            addCriterion("vender_remark <=", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLike(String value) {
            addCriterion("vender_remark like", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotLike(String value) {
            addCriterion("vender_remark not like", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIn(List<String> values) {
            addCriterion("vender_remark in", values, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotIn(List<String> values) {
            addCriterion("vender_remark not in", values, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkBetween(String value1, String value2) {
            addCriterion("vender_remark between", value1, value2, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotBetween(String value1, String value2) {
            addCriterion("vender_remark not between", value1, value2, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andPinIsNull() {
            addCriterion("pin is null");
            return (Criteria) this;
        }

        public Criteria andPinIsNotNull() {
            addCriterion("pin is not null");
            return (Criteria) this;
        }

        public Criteria andPinEqualTo(String value) {
            addCriterion("pin =", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotEqualTo(String value) {
            addCriterion("pin <>", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinGreaterThan(String value) {
            addCriterion("pin >", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinGreaterThanOrEqualTo(String value) {
            addCriterion("pin >=", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLessThan(String value) {
            addCriterion("pin <", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLessThanOrEqualTo(String value) {
            addCriterion("pin <=", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLike(String value) {
            addCriterion("pin like", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotLike(String value) {
            addCriterion("pin not like", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinIn(List<String> values) {
            addCriterion("pin in", values, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotIn(List<String> values) {
            addCriterion("pin not in", values, "pin");
            return (Criteria) this;
        }

        public Criteria andPinBetween(String value1, String value2) {
            addCriterion("pin between", value1, value2, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotBetween(String value1, String value2) {
            addCriterion("pin not between", value1, value2, "pin");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIsNull() {
            addCriterion("payment_confirm_time is null");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIsNotNull() {
            addCriterion("payment_confirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeEqualTo(Date value) {
            addCriterion("payment_confirm_time =", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotEqualTo(Date value) {
            addCriterion("payment_confirm_time <>", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeGreaterThan(Date value) {
            addCriterion("payment_confirm_time >", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("payment_confirm_time >=", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLessThan(Date value) {
            addCriterion("payment_confirm_time <", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("payment_confirm_time <=", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIn(List<Date> values) {
            addCriterion("payment_confirm_time in", values, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotIn(List<Date> values) {
            addCriterion("payment_confirm_time not in", values, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("payment_confirm_time between", value1, value2, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("payment_confirm_time not between", value1, value2, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIsNull() {
            addCriterion("coupon_detail_list is null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIsNotNull() {
            addCriterion("coupon_detail_list is not null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListEqualTo(String value) {
            addCriterion("coupon_detail_list =", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotEqualTo(String value) {
            addCriterion("coupon_detail_list <>", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListGreaterThan(String value) {
            addCriterion("coupon_detail_list >", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_detail_list >=", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLessThan(String value) {
            addCriterion("coupon_detail_list <", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLessThanOrEqualTo(String value) {
            addCriterion("coupon_detail_list <=", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLike(String value) {
            addCriterion("coupon_detail_list like", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotLike(String value) {
            addCriterion("coupon_detail_list not like", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIn(List<String> values) {
            addCriterion("coupon_detail_list in", values, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotIn(List<String> values) {
            addCriterion("coupon_detail_list not in", values, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListBetween(String value1, String value2) {
            addCriterion("coupon_detail_list between", value1, value2, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotBetween(String value1, String value2) {
            addCriterion("coupon_detail_list not between", value1, value2, "couponDetailList");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 17 16:27:59 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}