package bi.baiqiu.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class JdOrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.shop_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.pay_type
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_total_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private BigDecimal orderTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_payment
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private BigDecimal orderPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.freight_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private BigDecimal freightPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.seller_discount
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private BigDecimal sellerDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_state
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_start_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Date orderStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.order_end_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Date orderEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.consignee_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String consigneeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.item_info_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String itemInfoList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.vender_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String venderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.pin
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.modified
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.payment_confirm_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private Date paymentConfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_jd_order_info.coupon_detail_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    private String couponDetailList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.id
     *
     * @return the value of bi_jd_order_info.id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.id
     *
     * @param id the value for bi_jd_order_info.id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.shop_id
     *
     * @return the value of bi_jd_order_info.shop_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.shop_id
     *
     * @param shopId the value for bi_jd_order_info.shop_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_id
     *
     * @return the value of bi_jd_order_info.order_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_id
     *
     * @param orderId the value for bi_jd_order_info.order_id
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.pay_type
     *
     * @return the value of bi_jd_order_info.pay_type
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.pay_type
     *
     * @param payType the value for bi_jd_order_info.pay_type
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_total_price
     *
     * @return the value of bi_jd_order_info.order_total_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public BigDecimal getOrderTotalPrice() {
        return orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_total_price
     *
     * @param orderTotalPrice the value for bi_jd_order_info.order_total_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderTotalPrice(BigDecimal orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_payment
     *
     * @return the value of bi_jd_order_info.order_payment
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public BigDecimal getOrderPayment() {
        return orderPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_payment
     *
     * @param orderPayment the value for bi_jd_order_info.order_payment
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderPayment(BigDecimal orderPayment) {
        this.orderPayment = orderPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.freight_price
     *
     * @return the value of bi_jd_order_info.freight_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public BigDecimal getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.freight_price
     *
     * @param freightPrice the value for bi_jd_order_info.freight_price
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setFreightPrice(BigDecimal freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.seller_discount
     *
     * @return the value of bi_jd_order_info.seller_discount
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public BigDecimal getSellerDiscount() {
        return sellerDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.seller_discount
     *
     * @param sellerDiscount the value for bi_jd_order_info.seller_discount
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setSellerDiscount(BigDecimal sellerDiscount) {
        this.sellerDiscount = sellerDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_state
     *
     * @return the value of bi_jd_order_info.order_state
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_state
     *
     * @param orderState the value for bi_jd_order_info.order_state
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_remark
     *
     * @return the value of bi_jd_order_info.order_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_remark
     *
     * @param orderRemark the value for bi_jd_order_info.order_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_start_time
     *
     * @return the value of bi_jd_order_info.order_start_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Date getOrderStartTime() {
        return orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_start_time
     *
     * @param orderStartTime the value for bi_jd_order_info.order_start_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderStartTime(Date orderStartTime) {
        this.orderStartTime = orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.order_end_time
     *
     * @return the value of bi_jd_order_info.order_end_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Date getOrderEndTime() {
        return orderEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.order_end_time
     *
     * @param orderEndTime the value for bi_jd_order_info.order_end_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setOrderEndTime(Date orderEndTime) {
        this.orderEndTime = orderEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.consignee_info
     *
     * @return the value of bi_jd_order_info.consignee_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getConsigneeInfo() {
        return consigneeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.consignee_info
     *
     * @param consigneeInfo the value for bi_jd_order_info.consignee_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setConsigneeInfo(String consigneeInfo) {
        this.consigneeInfo = consigneeInfo == null ? null : consigneeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.item_info_list
     *
     * @return the value of bi_jd_order_info.item_info_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getItemInfoList() {
        return itemInfoList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.item_info_list
     *
     * @param itemInfoList the value for bi_jd_order_info.item_info_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setItemInfoList(String itemInfoList) {
        this.itemInfoList = itemInfoList == null ? null : itemInfoList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.vender_remark
     *
     * @return the value of bi_jd_order_info.vender_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getVenderRemark() {
        return venderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.vender_remark
     *
     * @param venderRemark the value for bi_jd_order_info.vender_remark
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setVenderRemark(String venderRemark) {
        this.venderRemark = venderRemark == null ? null : venderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.pin
     *
     * @return the value of bi_jd_order_info.pin
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.pin
     *
     * @param pin the value for bi_jd_order_info.pin
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.modified
     *
     * @return the value of bi_jd_order_info.modified
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.modified
     *
     * @param modified the value for bi_jd_order_info.modified
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.payment_confirm_time
     *
     * @return the value of bi_jd_order_info.payment_confirm_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public Date getPaymentConfirmTime() {
        return paymentConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.payment_confirm_time
     *
     * @param paymentConfirmTime the value for bi_jd_order_info.payment_confirm_time
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setPaymentConfirmTime(Date paymentConfirmTime) {
        this.paymentConfirmTime = paymentConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_jd_order_info.coupon_detail_list
     *
     * @return the value of bi_jd_order_info.coupon_detail_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public String getCouponDetailList() {
        return couponDetailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_jd_order_info.coupon_detail_list
     *
     * @param couponDetailList the value for bi_jd_order_info.coupon_detail_list
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    public void setCouponDetailList(String couponDetailList) {
        this.couponDetailList = couponDetailList == null ? null : couponDetailList.trim();
    }
}