package bi.baiqiu.pojo;

public class SaleCate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cate.id
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cate.ex
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    private Byte ex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cate.name
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cate.short_
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    private String short_;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cate.id
     *
     * @return the value of sale_cate.id
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cate.id
     *
     * @param id the value for sale_cate.id
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cate.ex
     *
     * @return the value of sale_cate.ex
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public Byte getEx() {
        return ex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cate.ex
     *
     * @param ex the value for sale_cate.ex
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public void setEx(Byte ex) {
        this.ex = ex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cate.name
     *
     * @return the value of sale_cate.name
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cate.name
     *
     * @param name the value for sale_cate.name
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cate.short
     *
     * @return the value of sale_cate.short
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public String getShort() {
        return short_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cate.short_
     *
     * @param short_ the value for sale_cate.short_
     *
     * @mbggenerated Tue Sep 26 19:25:54 CST 2017
     */
    public void setshort_(String short_) {
        this.short_ = short_ == null ? null : short_.trim();
    }
}