package bi.baiqiu.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ShopBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public ShopBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExIsNull() {
            addCriterion("ex is null");
            return (Criteria) this;
        }

        public Criteria andExIsNotNull() {
            addCriterion("ex is not null");
            return (Criteria) this;
        }

        public Criteria andExEqualTo(Byte value) {
            addCriterion("ex =", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExNotEqualTo(Byte value) {
            addCriterion("ex <>", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExGreaterThan(Byte value) {
            addCriterion("ex >", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExGreaterThanOrEqualTo(Byte value) {
            addCriterion("ex >=", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExLessThan(Byte value) {
            addCriterion("ex <", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExLessThanOrEqualTo(Byte value) {
            addCriterion("ex <=", value, "ex");
            return (Criteria) this;
        }

        public Criteria andExIn(List<Byte> values) {
            addCriterion("ex in", values, "ex");
            return (Criteria) this;
        }

        public Criteria andExNotIn(List<Byte> values) {
            addCriterion("ex not in", values, "ex");
            return (Criteria) this;
        }

        public Criteria andExBetween(Byte value1, Byte value2) {
            addCriterion("ex between", value1, value2, "ex");
            return (Criteria) this;
        }

        public Criteria andExNotBetween(Byte value1, Byte value2) {
            addCriterion("ex not between", value1, value2, "ex");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyIsNull() {
            addCriterion("erp_session_key is null");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyIsNotNull() {
            addCriterion("erp_session_key is not null");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyEqualTo(String value) {
            addCriterion("erp_session_key =", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyNotEqualTo(String value) {
            addCriterion("erp_session_key <>", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyGreaterThan(String value) {
            addCriterion("erp_session_key >", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyGreaterThanOrEqualTo(String value) {
            addCriterion("erp_session_key >=", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyLessThan(String value) {
            addCriterion("erp_session_key <", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyLessThanOrEqualTo(String value) {
            addCriterion("erp_session_key <=", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyLike(String value) {
            addCriterion("erp_session_key like", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyNotLike(String value) {
            addCriterion("erp_session_key not like", value, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyIn(List<String> values) {
            addCriterion("erp_session_key in", values, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyNotIn(List<String> values) {
            addCriterion("erp_session_key not in", values, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyBetween(String value1, String value2) {
            addCriterion("erp_session_key between", value1, value2, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andErpSessionKeyNotBetween(String value1, String value2) {
            addCriterion("erp_session_key not between", value1, value2, "erpSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyIsNull() {
            addCriterion("crm_session_key is null");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyIsNotNull() {
            addCriterion("crm_session_key is not null");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyEqualTo(String value) {
            addCriterion("crm_session_key =", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyNotEqualTo(String value) {
            addCriterion("crm_session_key <>", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyGreaterThan(String value) {
            addCriterion("crm_session_key >", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyGreaterThanOrEqualTo(String value) {
            addCriterion("crm_session_key >=", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyLessThan(String value) {
            addCriterion("crm_session_key <", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyLessThanOrEqualTo(String value) {
            addCriterion("crm_session_key <=", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyLike(String value) {
            addCriterion("crm_session_key like", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyNotLike(String value) {
            addCriterion("crm_session_key not like", value, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyIn(List<String> values) {
            addCriterion("crm_session_key in", values, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyNotIn(List<String> values) {
            addCriterion("crm_session_key not in", values, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyBetween(String value1, String value2) {
            addCriterion("crm_session_key between", value1, value2, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andCrmSessionKeyNotBetween(String value1, String value2) {
            addCriterion("crm_session_key not between", value1, value2, "crmSessionKey");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayIsNull() {
            addCriterion("is_search_alipay is null");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayIsNotNull() {
            addCriterion("is_search_alipay is not null");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayEqualTo(Byte value) {
            addCriterion("is_search_alipay =", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayNotEqualTo(Byte value) {
            addCriterion("is_search_alipay <>", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayGreaterThan(Byte value) {
            addCriterion("is_search_alipay >", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_search_alipay >=", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayLessThan(Byte value) {
            addCriterion("is_search_alipay <", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayLessThanOrEqualTo(Byte value) {
            addCriterion("is_search_alipay <=", value, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayIn(List<Byte> values) {
            addCriterion("is_search_alipay in", values, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayNotIn(List<Byte> values) {
            addCriterion("is_search_alipay not in", values, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayBetween(Byte value1, Byte value2) {
            addCriterion("is_search_alipay between", value1, value2, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andIsSearchAlipayNotBetween(Byte value1, Byte value2) {
            addCriterion("is_search_alipay not between", value1, value2, "isSearchAlipay");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNamePlatIsNull() {
            addCriterion("name_plat is null");
            return (Criteria) this;
        }

        public Criteria andNamePlatIsNotNull() {
            addCriterion("name_plat is not null");
            return (Criteria) this;
        }

        public Criteria andNamePlatEqualTo(String value) {
            addCriterion("name_plat =", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatNotEqualTo(String value) {
            addCriterion("name_plat <>", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatGreaterThan(String value) {
            addCriterion("name_plat >", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatGreaterThanOrEqualTo(String value) {
            addCriterion("name_plat >=", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatLessThan(String value) {
            addCriterion("name_plat <", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatLessThanOrEqualTo(String value) {
            addCriterion("name_plat <=", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatLike(String value) {
            addCriterion("name_plat like", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatNotLike(String value) {
            addCriterion("name_plat not like", value, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatIn(List<String> values) {
            addCriterion("name_plat in", values, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatNotIn(List<String> values) {
            addCriterion("name_plat not in", values, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatBetween(String value1, String value2) {
            addCriterion("name_plat between", value1, value2, "namePlat");
            return (Criteria) this;
        }

        public Criteria andNamePlatNotBetween(String value1, String value2) {
            addCriterion("name_plat not between", value1, value2, "namePlat");
            return (Criteria) this;
        }

        public Criteria andScIdIsNull() {
            addCriterion("sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(Integer value) {
            addCriterion("sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(Integer value) {
            addCriterion("sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(Integer value) {
            addCriterion("sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(Integer value) {
            addCriterion("sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(Integer value) {
            addCriterion("sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<Integer> values) {
            addCriterion("sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<Integer> values) {
            addCriterion("sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(Integer value1, Integer value2) {
            addCriterion("sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andStartIsNull() {
            addCriterion("start is null");
            return (Criteria) this;
        }

        public Criteria andStartIsNotNull() {
            addCriterion("start is not null");
            return (Criteria) this;
        }

        public Criteria andStartEqualTo(Date value) {
            addCriterionForJDBCDate("start =", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotEqualTo(Date value) {
            addCriterionForJDBCDate("start <>", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartGreaterThan(Date value) {
            addCriterionForJDBCDate("start >", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start >=", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartLessThan(Date value) {
            addCriterionForJDBCDate("start <", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start <=", value, "start");
            return (Criteria) this;
        }

        public Criteria andStartIn(List<Date> values) {
            addCriterionForJDBCDate("start in", values, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotIn(List<Date> values) {
            addCriterionForJDBCDate("start not in", values, "start");
            return (Criteria) this;
        }

        public Criteria andStartBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start between", value1, value2, "start");
            return (Criteria) this;
        }

        public Criteria andStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start not between", value1, value2, "start");
            return (Criteria) this;
        }

        public Criteria andStopIsNull() {
            addCriterion("stop is null");
            return (Criteria) this;
        }

        public Criteria andStopIsNotNull() {
            addCriterion("stop is not null");
            return (Criteria) this;
        }

        public Criteria andStopEqualTo(Date value) {
            addCriterionForJDBCDate("stop =", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopNotEqualTo(Date value) {
            addCriterionForJDBCDate("stop <>", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopGreaterThan(Date value) {
            addCriterionForJDBCDate("stop >", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stop >=", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopLessThan(Date value) {
            addCriterionForJDBCDate("stop <", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stop <=", value, "stop");
            return (Criteria) this;
        }

        public Criteria andStopIn(List<Date> values) {
            addCriterionForJDBCDate("stop in", values, "stop");
            return (Criteria) this;
        }

        public Criteria andStopNotIn(List<Date> values) {
            addCriterionForJDBCDate("stop not in", values, "stop");
            return (Criteria) this;
        }

        public Criteria andStopBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stop between", value1, value2, "stop");
            return (Criteria) this;
        }

        public Criteria andStopNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stop not between", value1, value2, "stop");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 26 14:45:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}