package bi.baiqiu.pojo;

import java.util.Date;

public class ShopBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.ex
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Byte ex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.erp_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private String erpSessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.crm_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private String crmSessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.is_search_alipay
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Byte isSearchAlipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name_plat
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private String namePlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.sc_id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Integer scId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.start
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.stop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private Date stop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.url
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    private String url;

    
    private ShopTvShowTablePojo shopTvShowTablePojo;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.ex
     *
     * @return the value of shop.ex
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Byte getEx() {
        return ex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.ex
     *
     * @param ex the value for shop.ex
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setEx(Byte ex) {
        this.ex = ex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.erp_session_key
     *
     * @return the value of shop.erp_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getErpSessionKey() {
        return erpSessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.erp_session_key
     *
     * @param erpSessionKey the value for shop.erp_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setErpSessionKey(String erpSessionKey) {
        this.erpSessionKey = erpSessionKey == null ? null : erpSessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.crm_session_key
     *
     * @return the value of shop.crm_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getCrmSessionKey() {
        return crmSessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.crm_session_key
     *
     * @param crmSessionKey the value for shop.crm_session_key
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setCrmSessionKey(String crmSessionKey) {
        this.crmSessionKey = crmSessionKey == null ? null : crmSessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.is_search_alipay
     *
     * @return the value of shop.is_search_alipay
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Byte getIsSearchAlipay() {
        return isSearchAlipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.is_search_alipay
     *
     * @param isSearchAlipay the value for shop.is_search_alipay
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setIsSearchAlipay(Byte isSearchAlipay) {
        this.isSearchAlipay = isSearchAlipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name_plat
     *
     * @return the value of shop.name_plat
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getNamePlat() {
        return namePlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name_plat
     *
     * @param namePlat the value for shop.name_plat
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setNamePlat(String namePlat) {
        this.namePlat = namePlat == null ? null : namePlat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.sc_id
     *
     * @return the value of shop.sc_id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.sc_id
     *
     * @param scId the value for shop.sc_id
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.start
     *
     * @return the value of shop.start
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.start
     *
     * @param start the value for shop.start
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.stop
     *
     * @return the value of shop.stop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public Date getStop() {
        return stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.stop
     *
     * @param stop the value for shop.stop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setStop(Date stop) {
        this.stop = stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.url
     *
     * @return the value of shop.url
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.url
     *
     * @param url the value for shop.url
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

	public ShopTvShowTablePojo getShopTvShowTablePojo() {
		return shopTvShowTablePojo;
	}

	public void setShopTvShowTablePojo(ShopTvShowTablePojo shopTvShowTablePojo) {
		this.shopTvShowTablePojo = shopTvShowTablePojo;
	}
}