package bi.baiqiu.pojo;

import java.util.Date;

public class FirstStart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firststart.id
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firststart.status
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firststart.jdp_modify
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    private Date jdpModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firststart.id
     *
     * @return the value of firststart.id
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firststart.id
     *
     * @param id the value for firststart.id
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firststart.status
     *
     * @return the value of firststart.status
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firststart.status
     *
     * @param status the value for firststart.status
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firststart.jdp_modify
     *
     * @return the value of firststart.jdp_modify
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public Date getJdpModify() {
        return jdpModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firststart.jdp_modify
     *
     * @param jdpModify the value for firststart.jdp_modify
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    public void setJdpModify(Date jdpModify) {
        this.jdpModify = jdpModify;
    }
}