package bi.baiqiu.mapper;

import bi.baiqiu.pojo.ShopBean;
import bi.baiqiu.pojo.ShopBeanExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ShopBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int countByExample(ShopBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int deleteByExample(ShopBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int insert(ShopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int insertSelective(ShopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    List<ShopBean> selectByExample(ShopBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    ShopBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShopBean record, @Param("example") ShopBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int updateByExample(@Param("record") ShopBean record, @Param("example") ShopBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int updateByPrimaryKeySelective(ShopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 26 14:45:32 CST 2017
     */
    int updateByPrimaryKey(ShopBean record);
 
    List<Map<String, String>>querySellerNick(ShopBean record);
    
    /** 
     * @Function: queryShopByScId 
     * @Description:根据部门简称查询店铺部门和店铺都在做的
     * @param scShort
     * @return    
     * @return List<ShopBean> 
     * @throws 
     *
     * Modification History:
     * Date         Author          Version            Description
     *---------------------------------------------------------
     * 2017年9月25日      Jared           v1.0.0              
    */
    List<ShopBean> queryShopByscShort(@Param("scShort")String scShort);
}