package bi.baiqiu.mapper;

import bi.baiqiu.pojo.JdOrderInfo;
import bi.baiqiu.pojo.JdOrderInfoExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jd.open.api.sdk.domain.order.OrderSearchInfo;

public interface JdOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int countByExample(JdOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int deleteByExample(JdOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int insert(JdOrderInfo record);

    
    int insertByJdOrderInfo(@Param("orderInfo")OrderSearchInfo orderInfo,@Param("shopId")String shopId);
  
    int insertByJdOrderInfoByBatch(@Param("orderInfo")List<OrderSearchInfo> orderInfo,@Param("shopId")String shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int insertSelective(JdOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    List<JdOrderInfo> selectByExample(JdOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    JdOrderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") JdOrderInfo record, @Param("example") JdOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int updateByExample(@Param("record") JdOrderInfo record, @Param("example") JdOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int updateByPrimaryKeySelective(JdOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_jd_order_info
     *
     * @mbggenerated Tue Oct 17 16:27:59 CST 2017
     */
    int updateByPrimaryKey(JdOrderInfo record);
    
    
    /** 
     * @Function: getSumByShopIdAndStartEndDate 
     * @Description:根据开始时间结束时间店铺id查询京东数据
     * @param shopId
     * @param startDate
     * @param endDate
     * @return    
     * @return Map<String,Object> 
     * @throws 
     *
     * Modification History:
     * Date         Author          Version            Description
     *---------------------------------------------------------
     * 2017年10月20日      Jared           v1.0.0              
    */
    Map<String, Object> getSaleByShopIdAndStartEndDate(@Param("shopId")String shopId,@Param("startDate")Date startDate,@Param("endDate")Date endDate);
}