package bi.baiqiu.mapper;

import bi.baiqiu.pojo.FirstStart;
import bi.baiqiu.pojo.FirstStartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirstStartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int countByExample(FirstStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int deleteByExample(FirstStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int insert(FirstStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int insertSelective(FirstStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    List<FirstStart> selectByExample(FirstStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    FirstStart selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") FirstStart record, @Param("example") FirstStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int updateByExample(@Param("record") FirstStart record, @Param("example") FirstStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int updateByPrimaryKeySelective(FirstStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firststart
     *
     * @mbggenerated Fri Sep 29 14:53:53 CST 2017
     */
    int updateByPrimaryKey(FirstStart record);
}